apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: my-wep-app

  ports:
    - port: 5000        #service port
      targetPort: 80    #Pod/container Port
     