apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: my-wep-app

  ports:
    - port: 8080        #service port
      targetPort: 80    #Pod/container Port
      nodePort: 30005   #any Port between 30000 and 32767 [OPTIONAL]